### ISSUE TITLE
Install guide

### ISSUE THREAD

**Issue by adamk22** [thomashrabe/AppRate#1]
Hi @thomashrabe,

Saw that you wrote your own app rate plugin in https://github.com/pushandplay/cordova-plugin-apprate/issues/311 do you have a basic install guide (I'd like to give it a try) or is it similar to how you install any other cordova plugins?

**Comment by thomashrabe** [comment]
Hi @adamk22  , I added a readme to answer your question. I still did not get Android to work. It compiles but the `AppRate` object is `null` when I run on my device.  Debug is ongoing, but feel free to check / fix yourself if you can. iOS is deployed on my app and works already.
